services:
  headscale-admin:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    image: ghcr.io/inlve/headscale-admin:1.0
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
