services:
  headscale:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
      - "${PANEL_APP_PORT_METRICS}:9090"
    volumes:
      - "./data/config:/etc/headscale"
      - "./data/data:/var/lib/headscale"
    command: ['serve']
    image: headscale/headscale:v0.23.0
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
